package com.dexing.findyou.bean;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.dexing.findyou.bean.FUser;

import com.dexing.findyou.bean.FUserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig fUserDaoConfig;

    private final FUserDao fUserDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        fUserDaoConfig = daoConfigMap.get(FUserDao.class).clone();
        fUserDaoConfig.initIdentityScope(type);

        fUserDao = new FUserDao(fUserDaoConfig, this);

        registerDao(FUser.class, fUserDao);
    }
    
    public void clear() {
        fUserDaoConfig.getIdentityScope().clear();
    }

    public FUserDao getFUserDao() {
        return fUserDao;
    }

}
